# DEV

services:
  bot:
    build: .
    image: metrik-bot:dev
    container_name: Metrik-Bot-Dev
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  postgres_db:
    image: postgres:18-alpine
    container_name: Metric-DB-Dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mentor_db}
      POSTGRES_USER: ${POSTGRES_USER:-db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db_password}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-db_user}", "-d", "${POSTGRES_DB:-mentor_db}" ]
      interval: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql

  migrations:
    image: metrik-bot:dev
    container_name: Metrik-Migrations-Dev
    environment:
      - PYTHONPATH=/app/src
    command: /app/.venv/bin/alembic upgrade head
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: "no"

  redis:
    image: redis:8-alpine
    container_name: Metrik-Redis-Dev
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  worker:
    image: metrik-bot:dev
    container_name: Metrik-Worker-Dev
    command: python -m taskiq worker tasks.broker:broker --fs-discover
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres_db:
        condition: service_healthy

  scheduler:
    image: metrik-bot:dev
    container_name: Metrik-Scheduler-Dev
    command: python -m taskiq scheduler tasks.tasks:scheduler
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy


volumes:
  postgres_data_dev:
  redis_data_dev: