"""init

Revision ID: 14dabae84b86
Revises: 
Create Date: 2026-02-17 10:16:44.645055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dabae84b86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('stepik_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('is_mentor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_stepik_users_user_id'), 'stepik_users', ['user_id'], unique=False)
    op.create_table('tg_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_tg_users_telegram_id'), 'tg_users', ['telegram_id'], unique=False)
    op.create_table('mentor_replies',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('mentor_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('stepik_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['stepik_users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_mentor_replies_course_id'), 'mentor_replies', ['course_id'], unique=False)
    op.create_index(op.f('ix_mentor_replies_mentor_id'), 'mentor_replies', ['mentor_id'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['stepik_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_course_id'), 'statistics', ['course_id'], unique=False)
    op.create_index(op.f('ix_statistics_mentor_id'), 'statistics', ['mentor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_mentor_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_course_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_mentor_replies_mentor_id'), table_name='mentor_replies')
    op.drop_index(op.f('ix_mentor_replies_course_id'), table_name='mentor_replies')
    op.drop_table('mentor_replies')
    op.drop_index(op.f('ix_tg_users_telegram_id'), table_name='tg_users')
    op.drop_table('tg_users')
    op.drop_index(op.f('ix_stepik_users_user_id'), table_name='stepik_users')
    op.drop_table('stepik_users')
    op.drop_table('courses')
    # ### end Alembic commands ###
