"""update mentor_statistic

Revision ID: 99f15cc9a01d
Revises: 551c633e6a4d
Create Date: 2026-03-04 15:51:52.209025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f15cc9a01d'
down_revision: Union[str, Sequence[str], None] = '551c633e6a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('stat_date', sa.Date(), nullable=False))
    op.add_column('statistics', sa.Column('total_comments', sa.Integer(), nullable=False))
    op.add_column('statistics', sa.Column('helpful_replies_count', sa.Integer(), nullable=False))
    op.add_column('statistics', sa.Column('help_index', sa.Float(), nullable=False))
    op.create_index('ix_stat_date_mentor_course', 'statistics', ['stat_date', 'mentor_id', 'course_id'], unique=True)
    op.create_index(op.f('ix_statistics_stat_date'), 'statistics', ['stat_date'], unique=False)
    op.drop_column('statistics', 'period_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_statistics_stat_date'), table_name='statistics')
    op.drop_index('ix_stat_date_mentor_course', table_name='statistics')
    op.drop_column('statistics', 'help_index')
    op.drop_column('statistics', 'helpful_replies_count')
    op.drop_column('statistics', 'total_comments')
    op.drop_column('statistics', 'stat_date')
    # ### end Alembic commands ###
