"""rename field

Revision ID: a6905be4fbbf
Revises: 14dabae84b86
Create Date: 2026-02-28 21:08:39.862275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6905be4fbbf'
down_revision: Union[str, Sequence[str], None] = '14dabae84b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskiq_schedules')
    op.add_column('mentor_replies', sa.Column('comment_created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('mentor_replies', 'stepik_created_at')
    op.drop_index(op.f('ix_stepik_users_user_id'), table_name='stepik_users')
    op.drop_index(op.f('ix_tg_users_telegram_id'), table_name='tg_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tg_users_telegram_id'), 'tg_users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_stepik_users_user_id'), 'stepik_users', ['user_id'], unique=False)
    op.add_column('mentor_replies', sa.Column('stepik_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('mentor_replies', 'comment_created_at')
    op.create_table('taskiq_schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('taskiq_schedules_pkey'))
    )
    # ### end Alembic commands ###
