"""add_role_and_is_active_fields

Revision ID: 4e8cdc62bd0b
Revises: 4aa789861005
Create Date: 2026-04-06 20:58:33.991171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e8cdc62bd0b'
down_revision: Union[str, Sequence[str], None] = '4aa789861005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('role', sa.String(length=20), server_default='visitor', nullable=False))
    op.add_column('tg_users', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('tg_users', 'is_admin')
    op.drop_column('tg_users', 'is_visitor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('is_visitor', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('tg_users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('tg_users', 'is_active')
    op.drop_column('tg_users', 'role')
    # ### end Alembic commands ###
