"""add_is_useful_comment_to_author_replies

Revision ID: a1b2c3d4e5f6
Revises: 4e8cdc62bd0b
Create Date: 2026-04-16 20:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '4e8cdc62bd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'author_replies',
        sa.Column(
            'is_useful_comment',
            sa.Boolean(),
            server_default='false',
            nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_replies', 'is_useful_comment')
    # ### end Alembic commands ###
