"""update_field

Revision ID: d988febd40a6
Revises: a6905be4fbbf
Create Date: 2026-02-28 21:32:46.046422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd988febd40a6'
down_revision: Union[str, Sequence[str], None] = 'a6905be4fbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'mentor_replies',
        'parent_comment_id',
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'mentor_replies',
        'parent_comment_id',
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###
