"""add is_from_mentor field

Revision ID: b8560a102216
Revises: d988febd40a6
Create Date: 2026-03-03 10:35:49.887796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8560a102216'
down_revision: Union[str, Sequence[str], None] = 'd988febd40a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_replies', sa.Column('is_from_mentor', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor_replies', 'is_from_mentor')
    # ### end Alembic commands ###
