"""init

Revision ID: cab4c767ede1
Revises: 
Create Date: 2026-03-05 14:50:37.174880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cab4c767ede1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('stepik_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('is_mentor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tg_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('author_replies',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('is_mentor_reply', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('comment_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['stepik_users.user_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_author_replies_author_id'), 'author_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_replies_course_id'), 'author_replies', ['course_id'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.Column('helpful_replies_count', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_seconds', sa.Float(), nullable=True),
    sa.Column('help_index', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['stepik_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stat_date_mentor_course', 'statistics', ['stat_date', 'mentor_id', 'course_id'], unique=True)
    op.create_index(op.f('ix_statistics_course_id'), 'statistics', ['course_id'], unique=False)
    op.create_index(op.f('ix_statistics_mentor_id'), 'statistics', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_statistics_stat_date'), 'statistics', ['stat_date'], unique=False)
    op.drop_table('taskiq_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskiq_schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('taskiq_schedules_pkey'))
    )
    op.drop_index(op.f('ix_statistics_stat_date'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_mentor_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_course_id'), table_name='statistics')
    op.drop_index('ix_stat_date_mentor_course', table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_author_replies_course_id'), table_name='author_replies')
    op.drop_index(op.f('ix_author_replies_author_id'), table_name='author_replies')
    op.drop_table('author_replies')
    op.drop_table('tg_users')
    op.drop_table('stepik_users')
    op.drop_table('courses')
    # ### end Alembic commands ###
