"""change_models

Revision ID: 551c633e6a4d
Revises: b8560a102216
Create Date: 2026-03-03 12:52:15.409771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '551c633e6a4d'
down_revision: Union[str, Sequence[str], None] = 'b8560a102216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_replies',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('is_mentor_reply', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('comment_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['stepik_users.user_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_author_replies_author_id'), 'author_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_replies_course_id'), 'author_replies', ['course_id'], unique=False)
    op.drop_index(op.f('ix_mentor_replies_course_id'), table_name='mentor_replies')
    op.drop_index(op.f('ix_mentor_replies_mentor_id'), table_name='mentor_replies')
    op.drop_table('mentor_replies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_replies',
    sa.Column('comment_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mentor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('comment_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_from_mentor', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('mentor_replies_course_id_fkey')),
    sa.ForeignKeyConstraint(['mentor_id'], ['stepik_users.user_id'], name=op.f('mentor_replies_mentor_id_fkey')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('mentor_replies_pkey'))
    )
    op.create_index(op.f('ix_mentor_replies_mentor_id'), 'mentor_replies', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentor_replies_course_id'), 'mentor_replies', ['course_id'], unique=False)
    op.drop_index(op.f('ix_author_replies_course_id'), table_name='author_replies')
    op.drop_index(op.f('ix_author_replies_author_id'), table_name='author_replies')
    op.drop_table('author_replies')
    # ### end Alembic commands ###
