"""add-fields-to-User

Revision ID: 4aa789861005
Revises: 3d45540754b6
Create Date: 2026-04-06 20:02:26.573108

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4aa789861005'
down_revision: str | Sequence[str] | None = '3d45540754b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tg_users',
        sa.Column(
            'is_admin', sa.Boolean(), server_default='false', nullable=False
        ),
    )
    op.add_column(
        'tg_users',
        sa.Column(
            'is_visitor', sa.Boolean(), server_default='false', nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'is_visitor')
    op.drop_column('tg_users', 'is_admin')
    # ### end Alembic commands ###
